#!/usr/bin/with-contenv bash

echo -- Environment --
env
echo -----------------
mkdir -p /slave
echo $SLAVE_SECRET> /slave/slave_secret
chmod o-rwx /slave/slave_secret
chown abc /slave/slave_secret
echo -- Slave Secret --
cat /slave/slave_secret
echo ------------------
echo --- Starting ---
echo exec s6-setuidgid abc   /usr/bin/smokeping --master-url=$MASTER_URL --cache-dir=/tmp --shared-secret=/slave/slave_secret --nodaemon --nosleep
sed -i 's/my .use_debuglog;/my \$use_debuglog=1;/g' /usr/share/perl5/vendor_perl/Smokeping.pm
# Add log message to show data sent to server
grep 'Sending to server:'  /usr/share/perl5/vendor_perl/Smokeping/Slave.pm || sed -i '75iSmokeping::do_debuglog("Sending to server:\\n$data_dump");' /usr/share/perl5/vendor_perl/Smokeping/Slave.pm
# Run tcptraceroute as root
chmod a+s /usr/bin/tcptraceroute
exec s6-setuidgid abc   /usr/bin/smokeping --master-url=$MASTER_URL --cache-dir=/tmp --shared-secret=/slave/slave_secret --nosleep --nodaemon

